### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by Xaeroxe** [kyren/luster#13]
Hi! I'm wondering what the future of this project will be now that Chucklefish has decided to not use Rust for their next title.

**Comment by kyren** [comment]
This project is completely unrelated to Chucklefish.

I've worked independently from Chucklefish since last year.  I guess you would describe me as "Chucklefish adjacent"?  (I've helped out with some things that were related to me since leaving, and am still available for consulting, etc.).

It was my choice to leave and it was very amicable, they're all still amazing people and they're my friends still.  It was unrelated to anything technical, Rust or otherwise.

`luster` is mostly just my own passion project, but I'm also going to use it for a project I'm working on, and some of it is kind of written with that project in mind.  It needs to mature a bit more first, though.
