### ISSUE TITLE
Split out gc_arena into its own repo

### ISSUE THREAD

**Issue by Herschel** [kyren/luster#23]
gc_arena and friends seem very useful! It could be a separate crate.

**Comment by kyren** [comment]
Yeah, agreed.  I've been meaning to do this and I'll do it very soon.

There are a couple of pretty solvable issues right now with gc_arena, so it'll give people a chance to look into that outside of luster.

I said I'd add finalization before splitting these out into their own crates, but I don't think I will (I don't know which finalization behavior people actually want, and luster needs very lua specific finalization behavior).  Since I'm not going to do that, there's nothing really blocking me.

**Comment by kyren** [comment]
done: https://github.com/kyren/gc-arena

**Comment by Herschel** [comment]
Thank you!
